[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
interprocess = { workspace = true }
tokio = { workspace = true }
protos = { path = "../protos" }
prost = { workspace = true }